# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# Recommended lints for Flutter apps, packages, and plugins
analyzer:
  errors:
    file_names: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # =====================
    # Const related rules
    # =====================
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # =====================
    # Style & readability
    # =====================
    always_use_package_imports: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unnecessary_this: true
    require_trailing_commas: true

    # =====================
    # Error prevention
    # =====================
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    no_logic_in_create_state: true
    use_key_in_widget_constructors: true

    # =====================
    # Performance
    # =====================
    use_rethrow_when_possible: true
