name: unique_supplement
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_html: ^3.0.0
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  get_it: ^8.2.0
  go_router: ^16.2.2
  google_fonts: ^6.3.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: asset/images/logo.png
  android: true
  ios: true
